workflows:
  songify-android:
    name: SongIfy Android

    max_build_duration: 120

    environment:
      java: 17

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Grant permissions
        script: |
          chmod +x gradlew

      - name: Build Release APK
        script: |
          ./gradlew assembleRelease

      - name: Build Release AAB
        script: |
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - your-email@gmail.com
